import {
  DiagramLayer,
  DiagramLink,
  DiagramNode,
  NodeSeverity,
  NodeShape,
  SystemGraph,
} from "@/types/diagram";

/**
 * Parses a Mermaid flowchart string into a SystemGraph JSON structure.
 * This parser specifically targets the "flowchart TD/LR" format generated by the AI.
 */
export function parseMermaidToJSON(mermaidCode: string): SystemGraph {
  const links: DiagramLink[] = [];
  const nodeId2Node: Record<string, DiagramNode> = {};
  const nodeId2ClassDef: Record<string, string> = {};
  const nodeDef2Styles: Record<string, string[]> = {};
  let direction: "TD" | "LR" = "TD";

  // 1. Determine direction
  if (
    mermaidCode.includes("flowchart LR") ||
    mermaidCode.includes("graph LR")
  ) {
    direction = "LR";
  }

  const lines = mermaidCode.split("\n");
  let currentSubgraphId: string | undefined;
  let currentSubgraphTitle: string | undefined;

  for (let line of lines) {
    line = line.trim();
    if (!line || line.startsWith("flowchart") || line.startsWith("graph"))
      continue;

    // 2. Handle Subgraphs
    // Supports: subgraph id["Title"], subgraph id ["Title"], subgraph id
    const subgraphMatch = line.match(/subgraph\s+([\w-]+)\s*(?:\["(.+?)"\])?/i);
    if (subgraphMatch) {
      currentSubgraphId = subgraphMatch[1];
      currentSubgraphTitle = subgraphMatch[2] || subgraphMatch[1];
      continue;
    }
    if (line === "end") {
      currentSubgraphId = undefined;
      currentSubgraphTitle = undefined;
      continue;
    }

    if (line.startsWith("style ") || line.startsWith("linkStyle ")) continue;

    // 3. Handle Nodes.
    // Register every inline node declaration on the line, and build a
    // "skeleton" copy where each `id["Label"]` is reduced to just `id`, so a
    // combined line like `R["Stripe Webhooks"] --> P` still yields its link.
    // Supports: A["Label"], B{"Label"}, C(("Label")), D[("Label")], E(["Label"]), F{{"Label"}}, G[/"Label"/], H[\"Label"\]
    const nodePattern =
      /([\w-]+)\s*(?:\["(.+?)"\]|\{"(.+?)"\}|\(\("(.+?)"\)\)|\[\("(.+?)"\)\]|\(\["(.+?)"\]\)|\{\{"(.+?)"\}\}|\[\/"(.+?)"\/\]|\[\\"(.+?)"\\\])/g;
    let skeleton = line;
    let nodeMatch: RegExpExecArray | null;
    while ((nodeMatch = nodePattern.exec(line)) !== null) {
      const [
        match,
        id,
        rectLabel,
        diamondLabel,
        circleLabel,
        cylinderLabel,
        stadiumLabel,
        hexLabel,
        paraLabel1,
        paraLabel2,
      ] = nodeMatch;
      const label =
        rectLabel ||
        diamondLabel ||
        circleLabel ||
        cylinderLabel ||
        stadiumLabel ||
        hexLabel ||
        paraLabel1 ||
        paraLabel2 ||
        id;

      let shape: NodeShape = "rectangle";
      if (diamondLabel) shape = "diamond";
      else if (circleLabel) shape = "circle";
      else if (cylinderLabel) shape = "cylinder";
      else if (stadiumLabel) shape = "stadium";
      else if (hexLabel) shape = "hexagon";
      else if (paraLabel1 || paraLabel2) shape = "parallelogram";

      // Deduplicate nodes
      if (!nodeId2Node[id]) {
        nodeId2Node[id] = {
          id,
          label,
          type: inferTypeFromLabel(label),
          shape,
          layer: inferLayerFromContext(label, currentSubgraphTitle),
          severity: "Medium", // Will be calculated in the second pass
          centralityScore: 0, // Pessimistic default is 0, will be calculated in the second pass
          subgraphId: currentSubgraphId,
          subgraphTitle: currentSubgraphTitle,
        };
      }

      // Replace inline R["Stripe Webhooks"] to id R for link registration.
      skeleton = skeleton.replace(match, id);
    }

    // 4. Handle Links (scanned against the skeleton so inline-declared
    // endpoints like `R["..."] --> P` resolve to `R --> P`).
    // Supports formats: A --> B, A -.-> B, A ==> B, and labeled variants A -- "Label" --> B, A -->|"Label"| B
    const linkMatch = skeleton.match(
      /([\w-]+)\s*(?:(?:--|-\.-|==)\s*"(.+?)"\s*(?:-->|-\.->|==>)|(?:-->|-\.->|==>)\|"(.+?)"\||(-->|-\.->|==>))\s*([\w-]+)/,
    );
    if (linkMatch) {
      const [full, source, label1, label2, , target] = linkMatch;
      let type: "sync" | "async" | "fallback" = "sync";
      if (full.includes("-.-")) type = "async";
      if (full.includes("==")) type = "fallback";

      links.push({
        source,
        target,
        label: label1 || label2,
        type,
      });

      // Ensure nodes mentioned in links exist (if they weren't defined explicitly)
      [source, target].forEach((nodeId) => {
        if (!nodeId2Node[nodeId]) {
          nodeId2Node[nodeId] = {
            id: nodeId,
            label: nodeId,
            type: "Unknown",
            shape: "rectangle",
            layer: "Other Services",
            severity: "Medium",
            centralityScore: 0,
            subgraphId: currentSubgraphId,
            subgraphTitle: currentSubgraphTitle,
          };
        }
      });
    }

    // classDef <names> <styleProps>   e.g. classDef database fill:#ccc,stroke:#333
    const classDefMatch = line.match(/^classDef\s+([\w,\s-]+?)\s+(.+)$/);
    if (classDefMatch) {
      const [, classDefs, styles] = classDefMatch;
      classDefs.split(",").forEach((classDef) => {
        nodeDef2Styles[classDef] = styles.split(",");
      });
      continue;
    }

    // class <id>[,<id>...] <className>   e.g. class J,K,L external
    const classMatch = line.match(/^class\s+([\w,\s-]+?)\s+([\w-]+)\s*$/);
    if (classMatch) {
      const [, classes, classDef] = classMatch;
      classes.split(",").forEach((cls) => {
        nodeId2ClassDef[cls] = classDef;
      });
    }
  }

  for (const [id, className] of Object.entries(nodeId2ClassDef)) {
    const node = nodeId2Node[id];
    if (node) {
      node.classes = nodeDef2Styles[className];
    }
  }

  const nodes: DiagramNode[] = Object.values(nodeId2Node);

  // 5. Calculate Severity (Second pass based on graph topology)
  // Initialize PageRank scores
  const pr: Record<string, number> = {};
  nodes.forEach((n) => (pr[n.id] = 1));

  const d = 0.85; // Damping factor
  const iterations = 20;

  for (let i = 0; i < iterations; i++) {
    const newPr: Record<string, number> = {};
    nodes.forEach((node) => {
      const incoming = links.filter((l) => (l.target as string) === node.id);
      let sum = 0;
      incoming.forEach((link) => {
        const sourceId = link.source as string;
        const sourceOutgoingCount = links.filter(
          (l) => (l.source as string) === sourceId,
        ).length;
        sum += pr[sourceId] / (sourceOutgoingCount || 1);
      });
      newPr[node.id] = 1 - d + d * sum;
    });
    Object.assign(pr, newPr);
  }

  nodes.forEach((node) => {
    // Scale by 10 and round to 1 decimal place for a clean UI presentation
    node.centralityScore = Math.round(pr[node.id] * 10 * 10) / 10;

    // Calculate severity based on the newly computed centrality score
    node.severity = calculateNodeSeverity(node);
  });

  return {
    nodes,
    links,
    metadata: {
      generatedAt: new Date().toISOString(),
      version: "1.0.0",
      direction,
    },
  };
}

/**
 * Heuristic to infer the component type from its label.
 */
function inferTypeFromLabel(label: string): string {
  const l = label.toLowerCase();
  if (
    l.includes("db") ||
    l.includes("database") ||
    l.includes("postgresql") ||
    l.includes("redis")
  )
    return "Database";
  if (l.includes("api") || l.includes("gateway") || l.includes("service"))
    return "Service";
  if (
    l.includes("app") ||
    l.includes("ui") ||
    l.includes("client") ||
    l.includes("frontend")
  )
    return "Frontend";
  if (l.includes("queue") || l.includes("kafka") || l.includes("rabbitmq"))
    return "Message Broker";
  return "Component";
}

/**
 * Heuristic to infer the architectural layer.
 */
function inferLayerFromContext(
  label: string,
  subgraphTitle?: string,
): DiagramLayer {
  const context = (label + " " + (subgraphTitle || "")).toLowerCase();
  if (context.includes("infra") || context.includes("cloud"))
    return "Infrastructure";
  if (
    context.includes("db") ||
    context.includes("database") ||
    context.includes("storage")
  )
    return "Database";
  if (
    context.includes("api") ||
    context.includes("server") ||
    context.includes("backend")
  )
    return "API";
  if (
    context.includes("ui") ||
    context.includes("app") ||
    context.includes("frontend")
  )
    return "Frontend";
  if (context.includes("external") || context.includes("auth"))
    return "External";
  return "Other Services";
}

/**
 * Calculate the severity/criticality of a node based on its computed centrality score.
 */
function calculateNodeSeverity(node: DiagramNode): NodeSeverity {
  const score = node.centralityScore || 0;

  if (score >= 5.0) return "Critical";
  if (score >= 3.0) return "High";
  if (score >= 2.0) return "Medium";

  return "Low";
}
